[0m16:12:34.021430 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 16:12:34.279031 | 2ca0898c-9281-4530-9c32-cca2adb2871b ==============================
[0m16:12:34.279031 [info ] [MainThread]: Running with dbt=1.7.9
[0m16:12:34.280047 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'profiles_dir': 'C:\\Users\\alblc\\.dbt', 'send_anonymous_usage_stats': 'True', 'version_check': 'True', 'cache_selected_only': 'False', 'target_path': 'None', 'use_colors': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'warn_error': 'None', 'introspect': 'True', 'debug': 'False', 'printer_width': '80', 'fail_fast': 'False', 'no_print': 'None', 'quiet': 'False', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'log_path': 'logs', 'indirect_selection': 'eager', 'write_json': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True'}
[0m16:12:34.280814 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\alblc\OneDrive\Desktop\nyc-taxi-lakehouse\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:12:34.281732 [debug] [MainThread]: Command `dbt run` failed at 16:12:34.281592 after 0.29 seconds
[0m16:12:34.282026 [debug] [MainThread]: Flushing usage events
